services:
  ms365-mcp:
    build: .
    restart: unless-stopped
    #ports:
    #  - "8000:8000"
    volumes:
      - ms365-data:/app/data
    environment:
      MS365_CLIENT_ID: "${MS365_CLIENT_ID}"
      MS365_TENANT_ID: "${MS365_TENANT_ID:-consumers}"
      TRANSPORT: http

volumes:
  ms365-data:
