"""Identifier helpers for tests.

Several suites predate the repository layer and still seed with `aiosqlite`
against the real migrated schema. That is a deliberate seam — it is how they
prove the read path copes with rows it did not write — but it bypasses the
models, which since migration 0017 are where a row's id comes from. These
helpers let such a seed name its own id, and let a test keep saying `m1`
where a uuid would be unreadable.
"""

from __future__ import annotations

from pincer.db.ids import Uuid7Sequence

_MINTED: dict[str, str] = {}
_SEQUENCE = Uuid7Sequence()
#: A fixed point in time, so a run's ids are stable and readable in failures.
_EPOCH_MS = 1_788_256_800_000


def seeded_id(label: str) -> str:
    """A stable UUIDv7 for a test's shorthand id — `seeded_id("m1")`.

    Tests read better naming rows `m1`, `m2`, `call-a` than pasting uuids, but
    `Uuid7` refuses anything that is not one (on SQLite too, deliberately: a
    lenient branch there would let the suite pass locally and fail in CI's
    postgres job). This keeps the shorthand and mints a real id behind it.

    Same label, same id, for the life of the process — so a test can seed with
    one and assert with the other. Ids are handed out in first-use order, so
    `m1` sorts before `m2` and reads that order back from the database.
    """
    if label not in _MINTED:
        _MINTED[label] = _SEQUENCE.next(_EPOCH_MS)
    return _MINTED[label]


def label_of(value: object) -> str:
    """The shorthand behind a `seeded_id`, for readable assertions.

    `[label_of(row["id"]) for row in rows] == ["m2", "m1"]` says what the test
    means; comparing raw uuids would not.
    """
    text = str(value)
    for label, minted in _MINTED.items():
        if minted == text:
            return label
    return text


#: A canonical UUIDv7-shaped id, generated by SQLite itself.
#:
#: Migration 0017 made these keys `NOT NULL` — an `INTEGER PRIMARY KEY` could
#: never hold NULL, and a row with a NULL key is worse than an error because
#: SQLAlchemy discards it on read. Raw-SQL seeds therefore have to supply one,
#: and doing it in the statement keeps the parameter lists untouched.
#:
#: These are NOT time-ordered — the timestamp field is random. That is fine
#: for seeds whose tests order by a real timestamp column, and anything that
#: does depend on key order should be writing through the models anyway.
SEED_ID_SQL = (
    "lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-7'||substr(hex(randomblob(2)),2)"
    "||'-8'||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))"
)
