"""The metadata every table model registers on — Alembic's `target_metadata`."""

from __future__ import annotations

from typing import Any

from sqlmodel import SQLModel

import pincer.models  # noqa: F401 - registers every table model on the metadata

metadata = SQLModel.metadata

#: The table Alembic records the current revision in, everywhere a
#: `MigrationContext` is configured — `env.py` for a real upgrade/downgrade,
#: and `tests/test_schema_drift.py` for a standalone comparison against
#: `metadata`. Not Alembic's default `alembic_version`, so it carries the
#: same `pincer_` prefix as every table the migrations manage.
VERSION_TABLE = "pincer_alembic_version"

#: Schema objects the migrations own by hand, with no model behind them.
#: Autogenerate must neither drop them nor try to create them.
HAND_WRITTEN_TABLES = frozenset(
    {
        # FTS5 virtual table over `pincer_memories` and its shadow tables
        # (SQLite only; kept in sync by triggers).
        "pincer_memories_fts",
        "pincer_memories_fts_config",
        "pincer_memories_fts_data",
        "pincer_memories_fts_docsize",
        "pincer_memories_fts_idx",
        # Dormant: created by 0001, read and written by nothing.
        "pincer_registry_skills",
        "pincer_expenses",
        "pincer_habits",
        "pincer_habit_checkins",
        "pincer_pomodoro_sessions",
        "pincer_discord_threads",
    }
)

#: Indexes whose definition differs per dialect and so cannot be one model
#: `Index`: `name COLLATE NOCASE` on SQLite, `lower(name)` on Postgres, and
#: the Postgres-only full-text index over memories (migration 0015).
HAND_WRITTEN_INDEXES = frozenset({"idx_phone_contacts_name", "idx_memories_search"})

#: Columns that exist on one dialect only, with no model behind them.
HAND_WRITTEN_COLUMNS = frozenset({("pincer_memories", "search_vector")})


def include_object(obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any) -> bool:
    """Alembic filter: leave hand-written and SQLite-internal objects alone."""
    if type_ == "table":
        return name not in HAND_WRITTEN_TABLES and not (name or "").startswith("sqlite_")
    if type_ == "index":
        return name not in HAND_WRITTEN_INDEXES
    if type_ == "column":
        table = getattr(getattr(obj, "table", None), "name", "")
        return (table, name) not in HAND_WRITTEN_COLUMNS
    return True


# ── SQLite reflection noise ──────────────────────────────────────────
#
# Two differences SQLite reports between the migrated schema and the models
# that are not worth a table rebuild, and that autogenerate must therefore not
# turn into one:
#
# * Primary keys reflect as nullable. 0001-0012 declared `TEXT PRIMARY KEY` /
#   `INTEGER PRIMARY KEY AUTOINCREMENT` without `NOT NULL`, and SQLite (unlike
#   Postgres) takes that literally. Every key is always set by the app.
# * A timestamp declared `TIMESTAMP` (phone_contacts.created_at, from 0001)
#   rather than `TEXT`. SQLite stores the same ISO text either way.


def compare_type(
    context: Any, inspected_column: Any, metadata_column: Any, inspected_type: Any, metadata_type: Any
) -> bool | None:
    """Alembic `compare_type` hook: `None` defers to the default comparison."""
    from pincer.db.types import IsoText

    if context.dialect.name == "sqlite" and isinstance(metadata_type, IsoText):
        return type(inspected_type).__name__.upper() not in ("TEXT", "TIMESTAMP", "DATETIME")
    return None


def is_sqlite_primary_key_nullability(
    dialect: str, table: str, column: str, nullable_before: bool, nullable_after: bool
) -> bool:
    """True for the primary-key nullability SQLite reports but Postgres does not.

    Direction-agnostic: the same difference appears as `True -> False` in an
    autogenerated `upgrade()` and as `False -> True` in its `downgrade()`.
    """
    if dialect != "sqlite" or nullable_before == nullable_after:
        return False
    model_table = metadata.tables.get(table)
    return model_table is not None and column in model_table.primary_key.columns


def drop_sqlite_noise(context: Any, revision: Any, directives: list[Any]) -> None:
    """Alembic `process_revision_directives` hook: strip the noise above from
    an autogenerated revision, so it only contains real changes.

    Both directions: under `render_as_batch` a leftover nullability change in
    `downgrade()` would rebuild every table it names.
    """

    dialect = context.dialect.name
    for script in directives:
        for upgrade_ops in (script.upgrade_ops, script.downgrade_ops):
            _drop_noise_ops(dialect, upgrade_ops)


def _drop_noise_ops(dialect: str, upgrade_ops: Any) -> None:
    from alembic.operations import ops

    for table_ops in list(upgrade_ops.ops):
        if not isinstance(table_ops, ops.ModifyTableOps):
            continue
        for op in list(table_ops.ops):
            if (
                isinstance(op, ops.AlterColumnOp)
                and op.modify_nullable is not None
                and op.modify_type is None
                and is_sqlite_primary_key_nullability(
                    dialect,
                    table_ops.table_name,
                    op.column_name,
                    bool(op.existing_nullable),
                    bool(op.modify_nullable),
                )
            ):
                table_ops.ops.remove(op)
        if not table_ops.ops:
            upgrade_ops.ops.remove(table_ops)
