"""The metadata every table model registers on — Alembic's `target_metadata`."""

from __future__ import annotations

from typing import Any

from sqlmodel import SQLModel

import pincer.models  # noqa: F401 - registers every table model on the metadata

metadata = SQLModel.metadata

#: Schema objects the migrations own by hand, with no model behind them.
#: Autogenerate must neither drop them nor try to create them.
HAND_WRITTEN_TABLES = frozenset(
    {
        # FTS5 virtual table over `memories` and its shadow tables (SQLite only;
        # kept in sync by triggers).
        "memories_fts",
        "memories_fts_config",
        "memories_fts_data",
        "memories_fts_docsize",
        "memories_fts_idx",
        # Dormant: created by 0001, read and written by nothing.
        "registry_skills",
        "expenses",
        "habits",
        "habit_checkins",
        "pomodoro_sessions",
        "discord_threads",
    }
)

#: Indexes whose definition differs per dialect and so cannot be one model
#: `Index`: `name COLLATE NOCASE` on SQLite, `lower(name)` on Postgres.
HAND_WRITTEN_INDEXES = frozenset({"idx_phone_contacts_name"})


def include_object(obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any) -> bool:
    """Alembic filter: leave hand-written and SQLite-internal objects alone."""
    if type_ == "table":
        return name not in HAND_WRITTEN_TABLES and not (name or "").startswith("sqlite_")
    if type_ == "index":
        return name not in HAND_WRITTEN_INDEXES
    return True


# ── SQLite reflection noise ──────────────────────────────────────────
#
# Two differences SQLite reports between the migrated schema and the models
# that are not worth a table rebuild, and that autogenerate must therefore not
# turn into one:
#
# * Primary keys reflect as nullable. 0001-0012 declared `TEXT PRIMARY KEY` /
#   `INTEGER PRIMARY KEY AUTOINCREMENT` without `NOT NULL`, and SQLite (unlike
#   Postgres) takes that literally. Every key is always set by the app.
# * A timestamp declared `TIMESTAMP` (phone_contacts.created_at, from 0001)
#   rather than `TEXT`. SQLite stores the same ISO text either way.


def compare_type(
    context: Any, inspected_column: Any, metadata_column: Any, inspected_type: Any, metadata_type: Any
) -> bool | None:
    """Alembic `compare_type` hook: `None` defers to the default comparison."""
    from pincer.db.types import IsoText

    if context.dialect.name == "sqlite" and isinstance(metadata_type, IsoText):
        return type(inspected_type).__name__.upper() not in ("TEXT", "TIMESTAMP", "DATETIME")
    return None


def is_sqlite_primary_key_nullability(
    dialect: str, table: str, column: str, nullable_before: bool, nullable_after: bool
) -> bool:
    """True for the primary-key nullability SQLite reports but Postgres does not."""
    if dialect != "sqlite" or not (nullable_before and not nullable_after):
        return False
    model_table = metadata.tables.get(table)
    return model_table is not None and column in model_table.primary_key.columns


def drop_sqlite_noise(context: Any, revision: Any, directives: list[Any]) -> None:
    """Alembic `process_revision_directives` hook: strip the noise above from
    an autogenerated revision, so it only contains real changes."""
    from alembic.operations import ops

    dialect = context.dialect.name
    for script in directives:
        for table_ops in list(script.upgrade_ops.ops):
            if not isinstance(table_ops, ops.ModifyTableOps):
                continue
            for op in list(table_ops.ops):
                if (
                    isinstance(op, ops.AlterColumnOp)
                    and op.modify_nullable is False
                    and op.modify_type is None
                    and is_sqlite_primary_key_nullability(
                        dialect, table_ops.table_name, op.column_name, bool(op.existing_nullable), False
                    )
                ):
                    table_ops.ops.remove(op)
            if not table_ops.ops:
                script.upgrade_ops.ops.remove(table_ops)
